### ISSUE TITLE
gensim version

### ISSUE THREAD

**Issue by baifengbai** [CyanYoung/english_chinese_translate_2#2]
Hello ,I have some problems when run represent.py ,may I ask which version of gensim you use?

**Comment by CyanYoung** [comment]
Hello, my gensim version is 3.5.0, you can tell me more details about your problem.

**Comment by baifengbai** [comment]
since I can't find 'en_word_vec.pkl' in feat/ folder ,so I trained one with text8 and save model using model.save ,but when load ,error occurs 
->'Word2Vec' object has no attribute 'keys'
or word_vecs should be  KeyedVectors? I tried to save model with KeyedVectors but error still,
-> embed_mat[ind]=word_vecs[word]    word2vecKeyedVectors has no attribute vectors

I am new to NLP ,so confused these days .keyi jiage weixin ma ...   wechat :bai7426

**Comment by CyanYoung** [comment]
yes, en_word_vec.pkl is loaded from Glove pre-trained word vectors.
